DROP TABLE IF EXISTS projects;

CREATE TABLE projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    technologies TEXT NOT NULL
    path_ TEXT NOT NULL,
);

CREATE TABLE contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    contact TEXT NOT NULL,
);

CREATE TABLE tech_skills (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
);

CREATE TABLE soft_skills (
     id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
);

